server:
  port: 8080

spring:
  application:
    name: kumple

  datasource:
    url: jdbc:postgresql://localhost:5433/kumple
    username: kumple
    password: kumple
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
